import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1788815592938 implements MigrationInterface {
    name = 'Init1788815592938'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."outbox_events_type_enum" AS ENUM('operation.created', 'operation.milestone_added', 'operation.document_added', 'operation.cost_added', 'client.created', 'invoice.exported', 'warehouse.receipt', 'warehouse.transfer', 'warehouse.pick', 'delivery.created', 'route.dispatched', 'delivery.delivered', 'delivery.failed')`);
        await queryRunner.query(`CREATE TABLE "outbox_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "type" "public"."outbox_events_type_enum" NOT NULL, "entity" character varying NOT NULL, "entityId" uuid NOT NULL, "payload" jsonb NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "dispatchedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6689a16c00d09b8089f6237f1d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52a799f51de1652614e8a8908f" ON "outbox_events" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b7668aa1aed034a544a7ad043" ON "outbox_events" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_a343a74015a0176940d4fb0e5f" ON "outbox_events" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16e890657b602bdc996dac3afe" ON "outbox_events" ("dispatchedAt") `);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "plate" character varying NOT NULL, "name" character varying NOT NULL, "capacity" integer, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_73306e2c24b126a5c02b1b8b988" UNIQUE ("tenantId", "plate"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ab940b0a05aed6c3d19d15ecb" ON "vehicles" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."routes_assignmenttype_enum" AS ENUM('own', 'carrier')`);
        await queryRunner.query(`CREATE TYPE "public"."routes_status_enum" AS ENUM('planned', 'dispatched', 'completed')`);
        await queryRunner.query(`CREATE TABLE "routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "date" date NOT NULL, "assignmentType" "public"."routes_assignmenttype_enum" NOT NULL, "vehicleId" uuid, "driverName" character varying, "carrierId" uuid, "status" "public"."routes_status_enum" NOT NULL DEFAULT 'planned', "originLat" double precision, "originLng" double precision, "estimatedKm" double precision, "dispatchedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_76100511cdfa1d013c859f01d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93e4f782932b7c0a332ab3d3cf" ON "routes" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68299bc40f96b61a550e0c7bf" ON "routes" ("date") `);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_status_enum" AS ENUM('pending', 'assigned', 'en_route', 'delivered', 'failed')`);
        await queryRunner.query(`CREATE TABLE "deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "operationId" uuid, "reference" character varying NOT NULL, "address" character varying NOT NULL, "lat" double precision, "lng" double precision, "routeId" uuid, "sequence" integer, "status" "public"."deliveries_status_enum" NOT NULL DEFAULT 'pending', "deliveredAt" TIMESTAMP WITH TIME ZONE, "receivedBy" character varying, "podPhotoKey" character varying, "podNote" character varying, "failureReason" character varying, CONSTRAINT "PK_a6ef225c5c5f0974e503bfb731f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b96ca323ddc668b52a2d57349b" ON "deliveries" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2641b5ea422e9127007197e689" ON "deliveries" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_065305fe84d25a910a6074c324" ON "deliveries" ("operationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ccb894cf08c2585ec04d1bc38" ON "deliveries" ("routeId") `);
        await queryRunner.query(`CREATE TABLE "carriers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "name" character varying NOT NULL, "contactEmail" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_fe886e72b3d9f67da3ce70f4368" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_054b8b10bc57a8a66bae1367cd" ON "carriers" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "client_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "email" character varying NOT NULL, "name" character varying NOT NULL, "passwordHash" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9980da9905e57c6d64388bee997" UNIQUE ("tenantId", "email"), CONSTRAINT "PK_fe74bfd4d01077395ee4204b553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ba3e7ad59593b65ab4103ea2e" ON "client_users" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3cd05fd13c044ffd22f5bf2ec1" ON "client_users" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b08a71cf48cbbd139d4742d61" ON "client_users" ("email") `);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "name" character varying NOT NULL, "code" character varying, "contactEmail" character varying, "contactName" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78708145905b919ba16977437b" ON "clients" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e921caf21faa2aab020476e4" ON "clients" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."operations_servicetype_enum" AS ENUM('freight', 'warehousing', 'last_mile', 'customs', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."operations_status_enum" AS ENUM('created', 'in_transit', 'in_warehouse', 'delivered', 'closed')`);
        await queryRunner.query(`CREATE TABLE "operations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "reference" character varying NOT NULL, "serviceType" "public"."operations_servicetype_enum" NOT NULL DEFAULT 'freight', "status" "public"."operations_status_enum" NOT NULL DEFAULT 'created', "origin" character varying, "destination" character varying, CONSTRAINT "PK_7b62d84d6f9912b975987165856" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14abd1e431801fcfe009198cad" ON "operations" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ad9cf90133fb2a16903aa8284" ON "operations" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cbbbf88818a509ed8c614f908" ON "operations" ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."rate_rules_chargetype_enum" AS ENUM('per_service', 'storage', 'handling', 'pick_pack', 'vas', 'last_mile')`);
        await queryRunner.query(`CREATE TYPE "public"."rate_rules_unit_enum" AS ENUM('flat', 'per_day', 'per_movement', 'per_item', 'per_unit')`);
        await queryRunner.query(`CREATE TYPE "public"."rate_rules_triggerstatus_enum" AS ENUM('created', 'in_transit', 'in_warehouse', 'delivered', 'closed')`);
        await queryRunner.query(`CREATE TABLE "rate_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "rateCardId" uuid NOT NULL, "chargeType" "public"."rate_rules_chargetype_enum" NOT NULL, "description" character varying NOT NULL, "rateMinor" bigint NOT NULL, "unit" "public"."rate_rules_unit_enum" NOT NULL, "triggerStatus" "public"."rate_rules_triggerstatus_enum", "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_350f7570197de5aebb4f0b97ae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_62ad92ea35d2251ca5167a836e" ON "rate_rules" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ceca75ef0b98f0230a267d29d" ON "rate_rules" ("rateCardId") `);
        await queryRunner.query(`CREATE TABLE "rate_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "name" character varying NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_54c4a5c4872b2339d848e5d9eb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04194a9a7a7d51c61487bd3ab5" ON "rate_cards" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c68afba714333b5491209a1439" ON "rate_cards" ("clientId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'approved', 'issued')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "number" character varying NOT NULL, "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "currency" character varying(3) NOT NULL DEFAULT 'USD', "totalMinor" bigint NOT NULL DEFAULT '0', "issuedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89c82485e364081f457b210120" ON "invoices" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9df936180710f9968da7cf4a5" ON "invoices" ("clientId") `);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "chargeItemId" uuid NOT NULL, "description" character varying NOT NULL, "quantity" integer NOT NULL, "rateMinor" bigint NOT NULL, "amountMinor" bigint NOT NULL, CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9ab2cd6bd30aeb2df8fb92d53" ON "invoice_lines" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f57f31e620fe759b452feb776" ON "invoice_lines" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_exports_status_enum" AS ENUM('exported', 'failed')`);
        await queryRunner.query(`CREATE TABLE "invoice_exports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "status" "public"."invoice_exports_status_enum" NOT NULL, "externalRef" character varying, "payload" jsonb NOT NULL, "error" character varying, "exportedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_09c3c19d588694f168e5b9d6a0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_121a0800cdf6593d6b12b0529c" ON "invoice_exports" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_73fa22df072a9f1da5a0f941ac" ON "invoice_exports" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."charge_items_chargetype_enum" AS ENUM('per_service', 'storage', 'handling', 'pick_pack', 'vas', 'last_mile')`);
        await queryRunner.query(`CREATE TABLE "charge_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "clientId" uuid NOT NULL, "operationId" uuid, "source" character varying, "chargeType" "public"."charge_items_chargetype_enum" NOT NULL, "description" character varying NOT NULL, "quantity" integer NOT NULL, "rateMinor" bigint NOT NULL, "amountMinor" bigint NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "rateRuleId" uuid, "invoiceId" uuid, CONSTRAINT "PK_4b68274171976afba023c91ef9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70dc1d5dcc78dc6272ccc0b553" ON "charge_items" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb5ecc20a8664d56f49e8a0bef" ON "charge_items" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_93e0248b6b3da21086e4f56994" ON "charge_items" ("operationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_58e0f2cfee6449a5b3e7e806e9" ON "charge_items" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."carrier_invoices_status_enum" AS ENUM('pending', 'reconciled', 'disputed')`);
        await queryRunner.query(`CREATE TABLE "carrier_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "supplier" character varying NOT NULL, "number" character varying NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "declaredMinor" bigint NOT NULL, "status" "public"."carrier_invoices_status_enum" NOT NULL DEFAULT 'pending', "reconciledAt" TIMESTAMP WITH TIME ZONE, "note" character varying, CONSTRAINT "PK_adb0a774ef28d26c965d8d62147" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ccec8b30302071c5c643e3530" ON "carrier_invoices" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8b1cefa379a46d40b7e571e83" ON "carrier_invoices" ("supplier") `);
        await queryRunner.query(`CREATE TABLE "carrier_invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "carrierInvoiceId" uuid NOT NULL, "operationId" uuid NOT NULL, "concept" character varying NOT NULL, "declaredMinor" bigint NOT NULL, "recordedMinor" bigint, "varianceMinor" bigint, CONSTRAINT "PK_9495e9df1849b693d3b690ebfea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e08a511bdee5652a84648062d3" ON "carrier_invoice_lines" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_63787375c3c9fac4bf354822ab" ON "carrier_invoice_lines" ("carrierInvoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a428972a02ea82644c8ecbea4a" ON "carrier_invoice_lines" ("operationId") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('receipt', 'transfer', 'pick', 'adjust')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "clientId" uuid NOT NULL, "sku" character varying NOT NULL, "type" "public"."stock_movements_type_enum" NOT NULL, "quantity" integer NOT NULL, "fromLocationId" uuid, "toLocationId" uuid, "reference" character varying, "recordedBy" uuid, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7dde280faf0d06b5b1b067b8ac" ON "stock_movements" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d118fa925e343f74b7dfe822e" ON "stock_movements" ("warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3392c6ff325b874048c46d2406" ON "stock_movements" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77f0fcdbb16372c4d878986324" ON "stock_movements" ("sku") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_c59f6ed1f70c17d2159ef2804af" UNIQUE ("tenantId", "code"), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c747b0a69a22b026c99bac8b10" ON "warehouses" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "stock_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "locationId" uuid NOT NULL, "clientId" uuid NOT NULL, "sku" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_e8c52e9baca6deafc9ef6e80461" UNIQUE ("tenantId", "locationId", "clientId", "sku"), CONSTRAINT "PK_52a266aa3e04b8ad1f01088f3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f039f0b854b6b35ff22bb7657f" ON "stock_items" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ec4e307da0a3f7fb3ad3c24f1" ON "stock_items" ("warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98300e6b22277d44ed99cdcec6" ON "stock_items" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d7f97c7a310a06a18ba6513dd" ON "stock_items" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c427528a56ee9c7e24fdf6edd1" ON "stock_items" ("sku") `);
        await queryRunner.query(`CREATE TYPE "public"."locations_kind_enum" AS ENUM('receiving', 'storage', 'staging', 'shipping')`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "code" character varying NOT NULL, "kind" "public"."locations_kind_enum" NOT NULL DEFAULT 'storage', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_f3b1a0f03455fa67e8b9c3e084b" UNIQUE ("warehouseId", "code"), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb2c7f27ed444aba2e33f76f8f" ON "locations" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e4f83b9faa7491b9f86294f53" ON "locations" ("warehouseId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'ops', 'finance', 'readonly')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "email" character varying NOT NULL, "name" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'ops', "passwordHash" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_7346b08032078107fce81e014f6" UNIQUE ("tenantId", "email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c58f7e88c286e5e3478960a998" ON "users" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('created', 'in_transit', 'in_warehouse', 'delivered', 'closed')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "operationId" uuid NOT NULL, "status" "public"."milestones_status_enum" NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "recordedBy" uuid, "note" character varying, CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8501bf24f533aaaaa462c35fbd" ON "milestones" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8faabbf45634792f3506ac2c8c" ON "milestones" ("operationId") `);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('bill_of_lading', 'commercial_invoice', 'packing_list', 'proof_of_delivery', 'customs', 'other')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "operationId" uuid NOT NULL, "type" "public"."documents_type_enum" NOT NULL DEFAULT 'other', "fileName" character varying NOT NULL, "storageKey" character varying NOT NULL, "contentType" character varying, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60f16e580e8deb01244205a435" ON "documents" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f852f7b8ac8867e07e9d5be02" ON "documents" ("operationId") `);
        await queryRunner.query(`CREATE TABLE "cost_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenantId" uuid NOT NULL, "operationId" uuid NOT NULL, "concept" character varying NOT NULL, "amountMinor" bigint NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "supplier" character varying, CONSTRAINT "PK_7c98b6ed12112ffb9b3f8369c97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b341dfc300da11db674c2e29b5" ON "cost_items" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1da4d6433ce83b26a4d9d603dd" ON "cost_items" ("operationId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_1da4d6433ce83b26a4d9d603dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b341dfc300da11db674c2e29b5"`);
        await queryRunner.query(`DROP TABLE "cost_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f852f7b8ac8867e07e9d5be02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60f16e580e8deb01244205a435"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8faabbf45634792f3506ac2c8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8501bf24f533aaaaa462c35fbd"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58f7e88c286e5e3478960a998"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e4f83b9faa7491b9f86294f53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb2c7f27ed444aba2e33f76f8f"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TYPE "public"."locations_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c427528a56ee9c7e24fdf6edd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d7f97c7a310a06a18ba6513dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98300e6b22277d44ed99cdcec6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ec4e307da0a3f7fb3ad3c24f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f039f0b854b6b35ff22bb7657f"`);
        await queryRunner.query(`DROP TABLE "stock_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c747b0a69a22b026c99bac8b10"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77f0fcdbb16372c4d878986324"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3392c6ff325b874048c46d2406"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d118fa925e343f74b7dfe822e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dde280faf0d06b5b1b067b8ac"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a428972a02ea82644c8ecbea4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63787375c3c9fac4bf354822ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e08a511bdee5652a84648062d3"`);
        await queryRunner.query(`DROP TABLE "carrier_invoice_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8b1cefa379a46d40b7e571e83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ccec8b30302071c5c643e3530"`);
        await queryRunner.query(`DROP TABLE "carrier_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."carrier_invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58e0f2cfee6449a5b3e7e806e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93e0248b6b3da21086e4f56994"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb5ecc20a8664d56f49e8a0bef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70dc1d5dcc78dc6272ccc0b553"`);
        await queryRunner.query(`DROP TABLE "charge_items"`);
        await queryRunner.query(`DROP TYPE "public"."charge_items_chargetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73fa22df072a9f1da5a0f941ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_121a0800cdf6593d6b12b0529c"`);
        await queryRunner.query(`DROP TABLE "invoice_exports"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_exports_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f57f31e620fe759b452feb776"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9ab2cd6bd30aeb2df8fb92d53"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9df936180710f9968da7cf4a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89c82485e364081f457b210120"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c68afba714333b5491209a1439"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04194a9a7a7d51c61487bd3ab5"`);
        await queryRunner.query(`DROP TABLE "rate_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ceca75ef0b98f0230a267d29d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62ad92ea35d2251ca5167a836e"`);
        await queryRunner.query(`DROP TABLE "rate_rules"`);
        await queryRunner.query(`DROP TYPE "public"."rate_rules_triggerstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rate_rules_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rate_rules_chargetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cbbbf88818a509ed8c614f908"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ad9cf90133fb2a16903aa8284"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14abd1e431801fcfe009198cad"`);
        await queryRunner.query(`DROP TABLE "operations"`);
        await queryRunner.query(`DROP TYPE "public"."operations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."operations_servicetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e921caf21faa2aab020476e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78708145905b919ba16977437b"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b08a71cf48cbbd139d4742d61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cd05fd13c044ffd22f5bf2ec1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ba3e7ad59593b65ab4103ea2e"`);
        await queryRunner.query(`DROP TABLE "client_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_054b8b10bc57a8a66bae1367cd"`);
        await queryRunner.query(`DROP TABLE "carriers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ccb894cf08c2585ec04d1bc38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_065305fe84d25a910a6074c324"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2641b5ea422e9127007197e689"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b96ca323ddc668b52a2d57349b"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b68299bc40f96b61a550e0c7bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93e4f782932b7c0a332ab3d3cf"`);
        await queryRunner.query(`DROP TABLE "routes"`);
        await queryRunner.query(`DROP TYPE "public"."routes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."routes_assignmenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ab940b0a05aed6c3d19d15ecb"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16e890657b602bdc996dac3afe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a343a74015a0176940d4fb0e5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b7668aa1aed034a544a7ad043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52a799f51de1652614e8a8908f"`);
        await queryRunner.query(`DROP TABLE "outbox_events"`);
        await queryRunner.query(`DROP TYPE "public"."outbox_events_type_enum"`);
    }

}
